version: "3.1"

services:
  web:
    image: zhironghuang/tools-web
    build:
        context: .
        dockerfile: Dockerfile  
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.toolsweb.rule=Host(`${HOST}`)
        - traefik.http.routers.toolsweb.entrypoints=web
        - traefik.http.routers.toolsweb.middlewares=http-redirect@file
        - traefik.http.routers.toolsweb-secured.rule=Host(`${HOST}`)
        - traefik.http.routers.toolsweb-secured.entrypoints=web-secured
        - traefik.http.routers.toolsweb-secured.tls.certresolver=le
        - traefik.http.routers.toolsweb-secured.middlewares=chain-no-auth@file
        - traefik.http.services.toolsweb-secured.loadbalancer.server.port=80 # it seems you always need to give traefik a port so it 'notices' the service
      restart_policy:
        condition: on-failure  
    environment:
      - "HOST=${HOST}"
      - "JWT_KEY=${JWT_KEY}"
      - "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}"
      - "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}"
      - "REDIS_ADDR=${REDIS_ADDR}"
      - "CONNECTION_STRING=${CONNECTION_STRING}"
      - "DB_DRIVER=${DB_DRIVER}"
      - "RESOURCE_VERSION=${GITHUB_RUN_ID}"
      - "ENABLE_SITEMAP=${ENABLE_SITEMAP}"
      - "SITEMAP_HTTPS=${SITEMAP_HTTPS}"
      - "GIN_MODE=${GIN_MODE}"
      - "TZ=America/New_York"
    networks:
      - proxy
        
networks:
  proxy:
    external: true
