name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:    
    if: "contains(github.event.head_commit.message, '[deploy only]')"
    name: deploy
    runs-on: self-hosted
    steps:      
    - uses: actions/checkout@v2
    - name: Deploy
      env:
        DB_DRIVER: ${{ secrets.DB_DRIVER }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        HOST: ${{ secrets.HOST }}
        JWT_KEY: ${{ secrets.JWT_KEY }}
        REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        ENABLE_SITEMAP: ${{ ENABLE_SITEMAP }}
        SITEMAP_HTTPS: ${{ SITEMAP_HTTPS }}
      run: |
        export DB_DRIVER GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET HOST JWT_KEY REDIS_ADDR CONNECTION_STRING ENABLE_SITEMAP SITEMAP_HTTPS
        docker stack deploy -c docker-compose.yml --with-registry-auth Tools
    
          