name: Docker Build CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Unit tests.
        run: go test -v ./...

  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    name: Build
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" > ~/cred.txt
        cat ~/cred.txt | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Clean Docker cred
      run: rm ~/cred.txt
    - name: Build using buildx
      run: | 
        docker buildx build \
          --platform linux/amd64,linux/arm/v7 --push \
          -t zhironghuang/tools-web:${{ github.sha }} .
    - name: Docker Logout
      run: |
        docker logout
        rm ~/.docker/config.json