name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Push Docker Image
      run: docker-compose push
  deploy:
    name: deploy
    needs: build
    runs-on: self-hosted
    steps:
    - name: Deploy
      env:
        DB_DRIVER: ${{ secrets.DB_DRIVER }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        HOST: ${{ secrets.HOST }}
        JWT_KEY: ${{ secrets.JWT_KEY }}
        REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      run: |
        export DB_DRIVER GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET HOST JWT_KEY REDIS_ADDR CONNECTION_STRING
        docker stack deploy -c docker-compose.yml Tools
    
          