name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Build using buildx
      run: | 
        docker buildx build \
          --platform linux/amd64,linux/arm/v7 \
          --output "type=image,push=false" \
          --file ./test/Dockerfile ./test
    - name: Push Docker Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: zhironghuang/tools-web
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,$${{ GITHUB_RUN_ID }}"
  deploy:
    name: deploy
    needs: build
    runs-on: self-hosted
    steps:      
    - uses: actions/checkout@v2
    - name: Deploy
      env:
        DB_DRIVER: ${{ secrets.DB_DRIVER }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        HOST: ${{ secrets.HOST }}
        JWT_KEY: ${{ secrets.JWT_KEY }}
        REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      run: |
        export DB_DRIVER GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET HOST JWT_KEY REDIS_ADDR CONNECTION_STRING
        docker stack deploy -c docker-compose.yml Tools
    
          