name: Docker Release CI

on:
  release: 
    types: [published]

jobs:
  update:
    name: Update Images
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" > ~/cred.txt
        cat ~/cred.txt | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Clean Docker Cred
      run: rm ~/cred.txt
    - name: Pull Docker Image
      run: docker pull zhironghuang/tools-web:${{ github.sha }}
    - name: Change Docker Tag
      run: docker tag zhironghuang/tools-web:${{ github.sha }} zhironghuang/tools-web:latest
    - name: Push Latest Image
      run: docker push zhironghuang/tools-web:latest
    - name: Docker Logout
      run: |
        docker logout
        rm ~/.docker/config.json

  deploy:
    name: deploy
    needs: update
    runs-on: self-hosted
    steps:      
    - uses: actions/checkout@v2
    - name: Deploy
      env:
        DB_DRIVER: ${{ secrets.DB_DRIVER }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        HOST: ${{ secrets.HOST }}
        JWT_KEY: ${{ secrets.JWT_KEY }}
        REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        ENABLE_SITEMAP: ${{ secrets.ENABLE_SITEMAP }}
        HTTPS: ${{ secrets.HTTPS }}
        GIN_MODE: ${{ secrets.GIN_MODE }}
      run: |
        export DB_DRIVER GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET HOST JWT_KEY REDIS_ADDR CONNECTION_STRING ENABLE_SITEMAP HTTPS GIN_MODE
        docker stack deploy -c docker-compose.yml --with-registry-auth Tools
    
          