name: Docker Release CI

on:
  release: 
    types: [published]

jobs:
  retag:
    runs-on: ubuntu-latest
    name: retag
    steps:
    - uses: actions/checkout@v2
    - name: Retag to latest
      uses: Z-M-Huang/docker-retag-curl@0.1.0
      with:
        repo: zhironghuang/tools-web
        old_tag: ${{ github.sha }}
        new_tag: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: deploy
    needs: retag
    runs-on: self-hosted
    steps:      
    - uses: actions/checkout@v2
    - name: Deploy
      env:
        DB_DRIVER: ${{ secrets.DB_DRIVER }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        HOST: ${{ secrets.HOST }}
        JWT_KEY: ${{ secrets.JWT_KEY }}
        REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        ENABLE_SITEMAP: ${{ secrets.ENABLE_SITEMAP }}
        HTTPS: ${{ secrets.HTTPS }}
        GIN_MODE: ${{ secrets.GIN_MODE }}
      run: |
        export DB_DRIVER GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET HOST JWT_KEY REDIS_ADDR CONNECTION_STRING ENABLE_SITEMAP HTTPS GIN_MODE
        docker stack deploy -c docker-compose.yml --with-registry-auth Tools

  tweet:
    runs-on: ubuntu-latest
    name: Tweet
    needs: deploy
    steps:
    - uses: actions/checkout@v2
    - name: Send Tweet
      uses: Z-M-Huang/TweetOnAction@v1
      with:
        consumer_key: ${{ secrets.CONSUMER_KEY }}
        consumer_secret: ${{ secrets.CONSUMER_SECRET }}
        access_token: ${{ secrets.ACCESS_TOKEN }}
        token_secret: ${{ secrets.TOKEN_SECRET }}
        content: "https://tools.zh-code.com just released a new version.\nPlease check it out for the new features!\nGithub:https://github.com/Z-M-Huang/Tools"
    
          